// =================================================================
// Emoji 猜詞語 - 擴充版題庫 (Associative/Ideographic Mode)
// =================================================================

export const EMOJI_QUESTIONS = [
  // =================================================================
  // 1. 成語類 (Idioms) - 經典與會意
  // =================================================================
  { id: 1, category: '成語', emojis: '🐔✈️🐶💃', answer: '雞飛狗跳' },
  { id: 2, category: '成語', emojis: '🐍➕🦶', answer: '畫蛇添足' },
  { id: 3, category: '成語', emojis: '🐄🎸', answer: '對牛彈琴' },
  { id: 4, category: '成語', emojis: '🪨1️⃣🐦🐦', answer: '一石二鳥' },
  { id: 5, category: '成語', emojis: '🐸⬇️🕳️', answer: '井底之蛙' },
  { id: 6, category: '成語', emojis: '🌳🧍‍♂️⏳🐰', answer: '守株待兔' },
  { id: 7, category: '成語', emojis: '👂🙈🔔', answer: '掩耳盜鈴' },
  { id: 8, category: '成語', emojis: '🦊👔🐯😤', answer: '狐假虎威' },
  { id: 9, category: '成語', emojis: '🙈🤚🐘', answer: '盲人摸象' },
  { id: 10, category: '成語', emojis: '🍵🏹🐍👻', answer: '杯弓蛇影' },
  { id: 11, category: '成語', emojis: '🗡️🚤🔍💎', answer: '刻舟求劍' },
  { id: 12, category: '成語', emojis: '🐺🍽️🐯😋', answer: '狼吞虎嚥' },
  { id: 13, category: '成語', emojis: '🐉✈️🦚💃', answer: '龍飛鳳舞' },
  { id: 14, category: '成語', emojis: '🦢👔🐔🐔🐔', answer: '鶴立雞群' },
  { id: 15, category: '成語', emojis: '🐔💬🦆❓', answer: '雞同鴨講' },
  { id: 16, category: '成語', emojis: '🐶😰🧱🦘', answer: '狗急跳牆' },
  { id: 17, category: '成語', emojis: '🌿🐍😱', answer: '打草驚蛇' },
  { id: 18, category: '成語', emojis: '🔪🐔⚠️🐵', answer: '殺雞儆猴' },
  { id: 19, category: '成語', emojis: '🐟💧😊', answer: '如魚得水' },
  { id: 20, category: '成語', emojis: '🐟⬇️🦢⬇️', answer: '沉魚落雁' },
  { id: 21, category: '成語', emojis: '3️⃣🧠2️⃣💭', answer: '三心二意' },
  { id: 22, category: '成語', emojis: '4️⃣📍🎵😢', answer: '四面楚歌' },
  { id: 23, category: '成語', emojis: '5️⃣🫀🛐', answer: '五體投地' },
  { id: 24, category: '成語', emojis: '7️⃣👄8️⃣👅', answer: '七嘴八舌' },
  { id: 25, category: '成語', emojis: '9️⃣🐄1️⃣🦰', answer: '九牛一毛' },
  { id: 26, category: '成語', emojis: '🔟✅🔟✨', answer: '十全十美' },
  { id: 27, category: '成語', emojis: '1️⃣🏹2️⃣🦅', answer: '一箭雙鵰' },
  { id: 28, category: '成語', emojis: '👁️🚫🔄👀', answer: '目不轉睛' },
  { id: 29, category: '成語', emojis: '🤚🏃🦶🌀', answer: '手忙腳亂' },
  { id: 30, category: '成語', emojis: '😊🌸💐🗣️', answer: '花言巧語' },
  { id: 31, category: '成語', emojis: '🐴🏃👀🌸', answer: '走馬看花' },
  { id: 32, category: '成語', emojis: '😞⬇️👤😔', answer: '垂頭喪氣' },
  { id: 33, category: '成語', emojis: '😊👁️😄', answer: '眉開眼笑' },
  { id: 34, category: '成語', emojis: '😠💢😤💥', answer: '氣急敗壞' },
  { id: 35, category: '成語', emojis: '❤️🫣💓🪢', answer: '提心吊膽' },
  { id: 36, category: '成語', emojis: '😴💤😑', answer: '無精打采' },
  { id: 37, category: '成語', emojis: '😊🎉🥳✨', answer: '興高采烈' },
  { id: 38, category: '成語', emojis: '🐦🐦🔇', answer: '鴉雀無聲' },
  { id: 39, category: '成語', emojis: '💓🐭😨', answer: '膽小如鼠' },
  { id: 40, category: '成語', emojis: '1️⃣🦰🚫👋', answer: '一毛不拔' },
  { id: 41, category: '成語', emojis: '🗡️🔙🤚🛡️', answer: '自相矛盾' },
  { id: 42, category: '成語', emojis: '🐯头🐍尾', answer: '虎頭蛇尾' },
  { id: 43, category: '成語', emojis: '👄🍯🗡️🧴', answer: '口蜜腹劍' },
  { id: 44, category: '成語', emojis: '👉🦌🗣️🐴', answer: '指鹿為馬' },
  { id: 45, category: '成語', emojis: '🖌️🐉👀✨', answer: '畫龍點睛' },
  { id: 46, category: '成語', emojis: '❄️🌨️🤲⚫🔥', answer: '雪中送炭' },
  { id: 47, category: '成語', emojis: '🌺🔛🌺', answer: '錦上添花' },
  { id: 48, category: '成語', emojis: '🚪🚶‍♂️⛰️👁️', answer: '開門見山' },
  { id: 49, category: '成語', emojis: '🔥➕🛢️', answer: '火上加油' },
  { id: 50, category: '成語', emojis: '🧑🌊🧑🌊', answer: '人山人海' },
  { id: 51, category: '成語', emojis: '1️⃣👄🩸⛲', answer: '一針見血' },
  { id: 52, category: '成語', emojis: '🚗💧🐴🐉', answer: '車水馬龍' },
  { id: 53, category: '成語', emojis: '👻⛏️👼🛠️', answer: '鬼斧神工' },
  { id: 54, category: '成語', emojis: '🚫🦵🏃‍♂️💨', answer: '不脛而走' },
  { id: 55, category: '成語', emojis: '🌬️👂💨', answer: '耳邊風' },
  { id: 56, category: '成語', emojis: '🙌🥔✋🥒', answer: '順手牽羊' },
  { id: 57, category: '成語', emojis: '🌧️🌅🌤️🌈', answer: '雨過天晴' },
  { id: 58, category: '成語', emojis: '🔭🍷⛲🥩', answer: '酒池肉林' },
  { id: 59, category: '成語', emojis: '🐓🥚🦴🔍', answer: '雞蛋裡挑骨頭' },
  { id: 60, category: '成語', emojis: '🌊🏞️🌄🚧', answer: '水落石出' },
  { id: 61, category: '成語', emojis: '💧💧🪨🔓', answer: '滴水穿石' },
  { id: 62, category: '成語', emojis: '🧣🕰️🤏⏳', answer: '分秒必爭' },
  { id: 63, category: '成語', emojis: '☁️🌫️⛰️🌲', answer: '雲深不知處' },
  { id: 64, category: '成語', emojis: '👀👂🚫🥜', answer: '充耳不聞' },
  { id: 65, category: '成語', emojis: '🧠🌪️💡', answer: '腦力激盪' },
  { id: 66, category: '成語', emojis: '🚪🤕🏔️🐯', answer: '放虎歸山' },
  { id: 67, category: '成語', emojis: '⚡👂🚫🎭', answer: '迅雷不及掩耳' },
  { id: 68, category: '成語', emojis: '1️⃣🗣️9️⃣🏺', answer: '一言九鼎' },
  { id: 69, category: '成語', emojis: '🐔🐦🐶☮️', answer: '雞犬不寧' },
  { id: 70, category: '成語', emojis: '🎣🐟🐟🆙', answer: '願者上鉤' },

  // =================================================================
  // 2. 流行語與網路梗 (Slang & Memes)
  // =================================================================
  { id: 71, category: '流行語', emojis: '🛋️😴🏳️', answer: '躺平' },
  { id: 72, category: '流行語', emojis: '👤😰🙈💬', answer: '社恐' },
  { id: 73, category: '流行語', emojis: '🔄📈😵‍💫', answer: '內卷' },
  { id: 74, category: '流行語', emojis: '🐶👀📱', answer: '單身狗' },
  { id: 75, category: '流行語', emojis: '💰👶', answer: '富二代' },
  { id: 76, category: '流行語', emojis: '🍋😫💔', answer: '檸檬精' },
  { id: 77, category: '流行語', emojis: '🐷🐷👧', answer: '豬隊友' },
  { id: 78, category: '流行語', emojis: '🔥🔥🔥👀', answer: '吃瓜群眾' },
  { id: 79, category: '流行語', emojis: '👋🏋️‍♂️', answer: '擺爛' },
  { id: 80, category: '流行語', emojis: '🐸☕', answer: '佛系' },
  { id: 81, category: '流行語', emojis: '💔👻', answer: '心累' },
  { id: 82, category: '流行語', emojis: '🧠🚪💧', answer: '腦子進水' },
  { id: 83, category: '流行語', emojis: '🍵🟢👯‍♀️', answer: '綠茶婊' },
  { id: 84, category: '流行語', emojis: '🙌😵🙌', answer: '暈倒' },
  { id: 85, category: '流行語', emojis: '👻👹🐍🧙‍♀️', answer: '牛鬼蛇神' },
  { id: 86, category: '流行語', emojis: '👁️👄👁️', answer: '傻眼' },
  { id: 87, category: '流行語', emojis: '🌈💨', answer: '彩虹屁' },
  { id: 88, category: '流行語', emojis: '🦴💀🦴', answer: '骨感' },
  { id: 89, category: '流行語', emojis: '🤴🦠', answer: '王子病' },
  { id: 90, category: '流行語', emojis: '👸🦠', answer: '公主病' },
  { id: 91, category: '流行語', emojis: '💍🦵', answer: '抱大腿' },
  { id: 92, category: '流行語', emojis: '🧊🍷', answer: '壓壓驚' },
  { id: 93, category: '流行語', emojis: '🙅‍♂️💊🍵', answer: '不要找碴' },
  { id: 94, category: '流行語', emojis: '🎹🎹😼', answer: '鍵盤俠' },
  { id: 95, category: '流行語', emojis: '🌪️🚣‍♂️', answer: '風向球' },
  { id: 96, category: '流行語', emojis: '🌊👨', answer: '海王' },
  { id: 97, category: '流行語', emojis: '⬆️🧛‍♀️', answer: '吸血鬼' },
  { id: 98, category: '流行語', emojis: '🧱🧱🧱', answer: '碰壁' },
  { id: 99, category: '流行語', emojis: '🎒🏃‍♂️', answer: '背包客' },
  { id: 100, category: '流行語', emojis: '📉🥗', answer: '吃土' },
  { id: 101, category: '流行語', emojis: '👻🌪️', answer: '人來瘋' },
  { id: 102, category: '流行語', emojis: '🕰️🛁', answer: '洗洗睡' },
  { id: 103, category: '流行語', emojis: '⛽🦆', answer: '加油鴨' },
  { id: 104, category: '流行語', emojis: '👐🏪', answer: '甩手掌櫃' },
  { id: 105, category: '流行語', emojis: '🚁👩', answer: '直升機父母' },
  { id: 106, category: '流行語', emojis: '🌚🕰️', answer: '月光族' },
  { id: 107, category: '流行語', emojis: '☁️🐕', answer: '雲養狗' },
  { id: 108, category: '流行語', emojis: '🚗🐢💨', answer: '龜速' },
  { id: 109, category: '流行語', emojis: '🤡🃏', answer: '小丑' },
  { id: 110, category: '流行語', emojis: '🥣🐔💊', answer: '心靈雞湯' },

  // =================================================================
  // 3. 電影與動漫 (Movies & Anime) - 經典重現
  // =================================================================
  { id: 111, category: '電影動漫', emojis: '🦁👑', answer: '獅子王' },
  { id: 112, category: '電影動漫', emojis: '❄️👸💙', answer: '冰雪奇緣' },
  { id: 113, category: '電影動漫', emojis: '🧙‍♂️💍🌋', answer: '魔戒' },
  { id: 114, category: '電影動漫', emojis: '🦸‍♂️🕷️', answer: '蜘蛛人' },
  { id: 115, category: '電影動漫', emojis: '🤖🚗', answer: '變形金剛' },
  { id: 116, category: '電影動漫', emojis: '🐼🥋', answer: '功夫熊貓' },
  { id: 117, category: '電影動漫', emojis: '⚡🧙‍♂️👓', answer: '哈利波特' },
  { id: 118, category: '電影動漫', emojis: '🚢🧊💏🏊', answer: '鐵達尼號' },
  { id: 119, category: '電影動漫', emojis: '👧🐷🛀🐉', answer: '神隱少女' },
  { id: 120, category: '電影動漫', emojis: '🦑🎮🚦🔫', answer: '魷魚遊戲' },
  { id: 121, category: '電影動漫', emojis: '🪳🏛️⬆️', answer: '寄生上流' },
  { id: 122, category: '電影動漫', emojis: '🧟‍♂️🚄💨', answer: '屍速列車' },
  { id: 123, category: '電影動漫', emojis: '😴💭😴💭🚂', answer: '全面啟動' },
  { id: 124, category: '電影動漫', emojis: '🦖🦕🏞️', answer: '侏羅紀公園' },
  { id: 125, category: '電影動漫', emojis: '🍫🏭🎟️', answer: '巧克力冒險工廠' },
  { id: 126, category: '電影動漫', emojis: '👽🚲🌕', answer: 'E.T.' },
  { id: 127, category: '電影動漫', emojis: '🎈🏠👴👦', answer: '天外奇蹟' },
  { id: 128, category: '電影動漫', emojis: '🤠🧸🚀', answer: '玩具總動員' },
  { id: 129, category: '電影動漫', emojis: '🐠🔍🌊', answer: '海底總動員' },
  { id: 130, category: '電影動漫', emojis: '🐜👨', answer: '蟻人' },
  { id: 131, category: '電影動漫', emojis: '🦇👨', answer: '蝙蝠俠' },
  { id: 132, category: '電影動漫', emojis: '🛡️🇺🇸💪', answer: '美國隊長' },
  { id: 133, category: '電影動漫', emojis: '😈👠🐶🧥', answer: '庫伊拉' },
  { id: 134, category: '電影動漫', emojis: '👠👗🕛🎃', answer: '灰姑娘' },
  { id: 135, category: '電影動漫', emojis: '🍎👸💤☠️', answer: '白雪公主' },
  { id: 136, category: '電影動漫', emojis: '🧚‍♂️🏴‍☠️🐊🕰️', answer: '彼得潘' },
  { id: 137, category: '電影動漫', emojis: '👹👹⚡🔪', answer: '鬼滅之刃' },
  { id: 138, category: '電影動漫', emojis: '👒🏴‍☠️🍖🤛', answer: '海賊王' },
  { id: 139, category: '電影動漫', emojis: '🏀🔴🔥👨‍🦰', answer: '灌籃高手' },
  { id: 140, category: '電影動漫', emojis: '🕵️‍♂️👓⚽🛹', answer: '名偵探柯南' },
  { id: 141, category: '電影動漫', emojis: '👊🧑‍🦲1️⃣', answer: '一拳超人' },
  { id: 142, category: '電影動漫', emojis: '🐉🔮7️⃣', answer: '七龍珠' },
  { id: 143, category: '電影動漫', emojis: '👶🖍️🐘👙', answer: '蠟筆小新' },
  { id: 144, category: '電影動漫', emojis: '🔵🐱🤖🕒', answer: '哆啦A夢' },
  { id: 145, category: '電影動漫', emojis: '🧽⭐️🍍🦀', answer: '海綿寶寶' },
  { id: 146, category: '電影動漫', emojis: '🍄🐢👸🔧', answer: '超級瑪利歐' },
  { id: 147, category: '電影動漫', emojis: '🚀🔪🤫⛽', answer: 'Among Us' },
  { id: 148, category: '電影動漫', emojis: '🏎️😡👨‍🦲👪', answer: '玩命關頭' },
  { id: 149, category: '電影動漫', emojis: '🦍🆚🦖', answer: '哥吉拉大戰金剛' },
  { id: 150, category: '電影動漫', emojis: '🧛‍♂️🐺❤️🌲', answer: '暮光之城' },
  { id: 151, category: '電影動漫', emojis: '🐯🚣‍♂️🌊', answer: '少年PI的奇幻漂流' },
  { id: 152, category: '電影動漫', emojis: '👮‍♂️🎤🍩', answer: '動物方城市' },
  { id: 153, category: '電影動漫', emojis: '🎸💀🏵️👵', answer: '可可夜總會' },
  { id: 154, category: '電影動漫', emojis: '👠😈👗', answer: '穿著Prada的惡魔' },
  { id: 155, category: '電影動漫', emojis: '🐺📉💰', answer: '華爾街之狼' },
  { id: 156, category: '電影動漫', emojis: '🍫🏃‍♂️📦', answer: '阿甘正傳' },
  { id: 157, category: '電影動漫', emojis: '🕶️💊💻🐇', answer: '駭客任務' },
  { id: 158, category: '電影動漫', emojis: '🦁🦓🦒🦛', answer: '馬達加斯加' },
  { id: 159, category: '電影動漫', emojis: '🧟‍♂️🧟‍♀️🏠🌿', answer: '植物大戰殭屍' },
  { id: 160, category: '電影動漫', emojis: '🧱⛏️💎🗡️', answer: 'Minecraft' },

  // =================================================================
  // 4. 華語流行歌曲 (Mandarin Pop Songs) - 聽歌猜名
  // =================================================================
  { id: 161, category: '華語歌曲', emojis: '🗣️🤍🎈', answer: '告白氣球' },
  { id: 162, category: '華語歌曲', emojis: '🌾👃', answer: '稻香' },
  { id: 163, category: '華語歌曲', emojis: '👂👩💬', answer: '聽媽媽的話' },
  { id: 164, category: '華語歌曲', emojis: '🐉🌪️', answer: '龍捲風' },
  { id: 165, category: '華語歌曲', emojis: '💡🗓️🌌', answer: '光年之外' },
  { id: 166, category: '華語歌曲', emojis: '🔴👠', answer: '紅色高跟鞋' },
  { id: 167, category: '華語歌曲', emojis: '🌧️🚫🛑', answer: '雨一直下' },
  { id: 168, category: '華語歌曲', emojis: '🕺💃👯‍♀️', answer: '三天三夜' },
  { id: 169, category: '華語歌曲', emojis: '🔟📅', answer: '十年' },
  { id: 170, category: '華語歌曲', emojis: '🦐☁️', answer: '蝦米' },
  { id: 171, category: '華語歌曲', emojis: '🐟🎹', answer: '魚仔' },
  { id: 172, category: '華語歌曲', emojis: '🙅‍♂️💊🐟', answer: '不將就' },
  { id: 173, category: '華語歌曲', emojis: '🐂🤠', answer: '牛仔很忙' },
  { id: 174, category: '華語歌曲', emojis: '🧠🚮⛰️海', answer: '腦海' },
  { id: 175, category: '華語歌曲', emojis: '👯‍♀️👯‍♀️', answer: '姊妹' },
  { id: 176, category: '華語歌曲', emojis: '🐯🐯', answer: '兩隻老虎' },
  { id: 177, category: '華語歌曲', emojis: '🛸👦', answer: '太空人' },
  { id: 178, category: '華語歌曲', emojis: '🌃🌙✨', answer: '城裡的月光' },
  { id: 179, category: '華語歌曲', emojis: '🤫🤐', answer: '安靜' },
  { id: 180, category: '華語歌曲', emojis: '🎒🏫', answer: '那些年' },
  { id: 181, category: '華語歌曲', emojis: '🤏🤲🍀', answer: '小幸運' },
  { id: 182, category: '華語歌曲', emojis: '🧘‍♂️🧘‍♀️', answer: '修煉愛情' },
  { id: 183, category: '華語歌曲', emojis: '🚫🖐️🚫👴', answer: '不老傳說' },
  { id: 184, category: '華語歌曲', emojis: '🚶‍♂️🛣️', answer: '平凡之路' },
  { id: 185, category: '華語歌曲', emojis: '🍎💥', answer: '小蘋果' },
  { id: 186, category: '華語歌曲', emojis: '🦋🦋🐝', answer: '甜蜜蜜' },
  { id: 187, category: '華語歌曲', emojis: '🌙🔦', answer: '月亮代表我的心' },
  { id: 188, category: '華語歌曲', emojis: '🥃🐔', answer: 'Mojito' },
  { id: 189, category: '華語歌曲', emojis: '👨‍🎤👩‍🎤', answer: '演員' },
  { id: 190, category: '華語歌曲', emojis: '🍄🍄', answer: '蘑菇蘑菇' },

  // =================================================================
  // 5. 台灣特色與生活 (Taiwan & Local Life)
  // =================================================================
  { id: 191, category: '台灣特色', emojis: '🗼🇹🇼101', answer: '台北101' },
  { id: 192, category: '台灣特色', emojis: '🧋🖤⚫', answer: '珍珠奶茶' },
  { id: 193, category: '台灣特色', emojis: '🤢👃⬜🤤', answer: '臭豆腐' },
  { id: 194, category: '台灣特色', emojis: '🍍🍰📦', answer: '鳳梨酥' },
  { id: 195, category: '台灣特色', emojis: '🎶🚚🗑️🏃', answer: '垃圾車' },
  { id: 196, category: '台灣特色', emojis: '🧾🎰🤞', answer: '統一發票' },
  { id: 197, category: '台灣特色', emojis: '🏍️🛵🛵🌊', answer: '機車瀑布' },
  { id: 198, category: '台灣特色', emojis: '🚲💳🚇', answer: '悠遊卡' },
  { id: 199, category: '台灣特色', emojis: '🏪2️⃣4️⃣', answer: '便利商店' },
  { id: 200, category: '台灣特色', emojis: '🍗🍱', answer: '雞腿便當' },
  { id: 201, category: '台灣特色', emojis: '🥚🍳🦪', answer: '蚵仔煎' },
  { id: 202, category: '台灣特色', emojis: '🐷🩸🍰', answer: '豬血糕' },
  { id: 203, category: '台灣特色', emojis: '🍚🐷🥜', answer: '滷肉飯' },
  { id: 204, category: '台灣特色', emojis: '🌃🛒🍢', answer: '夜市' },
  { id: 205, category: '台灣特色', emojis: '🥤⭕❌', answer: '手搖飲' },
  { id: 206, category: '台灣特色', emojis: '🦁🗣️', answer: '獅子頭' },
  { id: 207, category: '台灣特色', emojis: '👴🌳☕', answer: '榕樹下' },
  { id: 208, category: '台灣特色', emojis: '🙏🧧🏯', answer: '拜拜' },
  { id: 209, category: '台灣特色', emojis: '🚑🏥😷', answer: '健保' },
  { id: 210, category: '台灣特色', emojis: '🔴🟠🚲', answer: 'YouBike' },
  { id: 211, category: '台灣特色', emojis: '🔴包', answer: '紅包' },
  { id: 212, category: '台灣特色', emojis: '🏮🐉🚣', answer: '端午節' },
  { id: 213, category: '台灣特色', emojis: '🌕🥮🔥', answer: '中秋節' },
  { id: 214, category: '台灣特色', emojis: '🧨🦁💃', answer: '春節' },
  { id: 215, category: '台灣特色', emojis: '🚄💨', answer: '高鐵' },
  { id: 216, category: '台灣特色', emojis: '⛰️🚂🌳', answer: '阿里山小火車' },
  { id: 217, category: '台灣特色', emojis: '🚤🏝️🌞', answer: '澎湖' },
  { id: 218, category: '台灣特色', emojis: '🦌🌾', answer: '鹿港' },
  { id: 219, category: '台灣特色', emojis: '👸👸👸', answer: '媽祖' },
  { id: 220, category: '台灣特色', emojis: '🧱🌧️🌬️', answer: '新竹風' },

  // =================================================================
  // 6. 食物與飲料 (Food & Drinks)
  // =================================================================
  { id: 221, category: '食物', emojis: '🍕🇮🇹', answer: '披薩' },
  { id: 222, category: '食物', emojis: '🍔🍟', answer: '漢堡套餐' },
  { id: 223, category: '食物', emojis: '🍣🍙', answer: '壽司' },
  { id: 224, category: '食物', emojis: '🍜🥩', answer: '牛肉麵' },
  { id: 225, category: '食物', emojis: '🥟🥢', answer: '水餃' },
  { id: 226, category: '食物', emojis: '🥐☕🇫🇷', answer: '可頌' },
  { id: 227, category: '食物', emojis: '🍦🍫', answer: '冰淇淋' },
  { id: 228, category: '食物', emojis: '🍿🎬', answer: '爆米花' },
  { id: 229, category: '食物', emojis: '🥞🍯', answer: '鬆餅' },
  { id: 230, category: '食物', emojis: '🥗🍅🥒', answer: '沙拉' },
  { id: 231, category: '食物', emojis: '🥩🔥🍴', answer: '牛排' },
  { id: 232, category: '食物', emojis: '🦞🦀🦐', answer: '海鮮' },
  { id: 233, category: '食物', emojis: '🧀🍷', answer: '起司' },
  { id: 234, category: '食物', emojis: '☕🥛☁️', answer: '拿鐵' },
  { id: 235, category: '食物', emojis: '🍋🥤', answer: '檸檬水' },
  { id: 236, category: '食物', emojis: '🍷🍇', answer: '紅酒' },
  { id: 237, category: '食物', emojis: '🍺🍻', answer: '啤酒' },
  { id: 238, category: '食物', emojis: '🍉🥤🧊', answer: '西瓜汁' },
  { id: 239, category: '食物', emojis: '🥯🍩', answer: '貝果' },
  { id: 240, category: '食物', emojis: '🍮🍮', answer: '布丁' },
  { id: 241, category: '食物', emojis: '🌭🥖', answer: '熱狗' },
  { id: 242, category: '食物', emojis: '🌮🇲🇽', answer: 'Taco' },
  { id: 243, category: '食物', emojis: '🥓🍳', answer: '培根蛋' },
  { id: 244, category: '食物', emojis: '🥣🥛', answer: '麥片' },
  { id: 245, category: '食物', emojis: '🍯🐝', answer: '蜂蜜' },
  { id: 246, category: '食物', emojis: '🍎🥧', answer: '蘋果派' },
  { id: 247, category: '食物', emojis: '🥑🍞', answer: '酪梨吐司' },
  { id: 248, category: '食物', emojis: '🥥🌴💧', answer: '椰子水' },
  { id: 249, category: '食物', emojis: '🍫🍪', answer: '巧克力餅乾' },
  { id: 250, category: '食物', emojis: '🍝🔴🥩', answer: '義大利麵' },

  // =================================================================
  // 7. 生活用品與品牌 (Objects & Brands)
  // =================================================================
  { id: 251, category: '物品', emojis: '🍎📱', answer: 'iPhone' },
  { id: 252, category: '物品', emojis: '🍎💻', answer: 'MacBook' },
  { id: 253, category: '物品', emojis: '🧜‍♀️☕', answer: '星巴克' },
  { id: 254, category: '物品', emojis: 'Ⓜ️🍔🍟', answer: '麥當勞' },
  { id: 255, category: '物品', emojis: '🚗⚡🔌', answer: '特斯拉' },
  { id: 256, category: '物品', emojis: '🐎🏎️🔴', answer: '法拉利' },
  { id: 257, category: '物品', emojis: '👻👓', answer: '隱形眼鏡' },
  { id: 258, category: '物品', emojis: '💙🦷🎧', answer: '藍牙耳機' },
  { id: 259, category: '物品', emojis: '🤖🧹', answer: '掃地機器人' },
  { id: 260, category: '物品', emojis: '💨💇‍♀️', answer: '吹風機' },
  { id: 261, category: '物品', emojis: '☔👢', answer: '雨鞋' },
  { id: 262, category: '物品', emojis: '😷🏥', answer: '口罩' },
  { id: 263, category: '物品', emojis: '🧴🤲🦠', answer: '乾洗手' },
  { id: 264, category: '物品', emojis: '🔋⚡📱', answer: '行動電源' },
  { id: 265, category: '物品', emojis: '🦷🖌️', answer: '牙刷' },
  { id: 266, category: '物品', emojis: '🚽🧻', answer: '衛生紙' },
  { id: 267, category: '物品', emojis: '📸🤳', answer: '自拍棒' },
  { id: 268, category: '物品', emojis: '🎮🕹️', answer: '遙控器' },
  { id: 269, category: '物品', emojis: '📺🖥️', answer: '電視' },
  { id: 270, category: '物品', emojis: '🧊📦', answer: '冰箱' },
  { id: 271, category: '物品', emojis: '🧼🚿', answer: '肥皂' },
  { id: 272, category: '物品', emojis: '🕶️☀️', answer: '太陽眼鏡' },
  { id: 273, category: '物品', emojis: '🎒🏫', answer: '書包' },
  { id: 274, category: '物品', emojis: '💍💎', answer: '鑽戒' },
  { id: 275, category: '物品', emojis: '⌚🏃‍♂️', answer: '運動手錶' },
  { id: 276, category: '物品', emojis: '🕯️🔥', answer: '蠟燭' },
  { id: 277, category: '物品', emojis: '🧸🛌', answer: '泰迪熊' },
  { id: 278, category: '物品', emojis: '🎸🎵', answer: '吉他' },
  { id: 279, category: '物品', emojis: '🎹🎹', answer: '鋼琴' },
  { id: 280, category: '物品', emojis: '🎻🎵', answer: '小提琴' },
  { id: 281, category: '物品', emojis: '✔️👟', answer: 'Nike' },
  { id: 282, category: '物品', emojis: '🐈‍⬛🚚', answer: '黑貓宅急便' },
  { id: 283, category: '物品', emojis: '🐼🛵🍲', answer: 'Foodpanda' },
  { id: 284, category: '物品', emojis: '⬛⬛🛵🍔', answer: 'UberEats' },
  { id: 285, category: '物品', emojis: '🏪7️⃣1️⃣1️⃣', answer: '7-11' },
  { id: 286, category: '物品', emojis: '🧴☀️⛱️', answer: '防曬乳' },
  { id: 287, category: '物品', emojis: '🔦🌑', answer: '手電筒' },
  { id: 288, category: '物品', emojis: '✂️📄', answer: '剪刀' },
  { id: 289, category: '物品', emojis: '🔧🔨', answer: '工具箱' },
  { id: 290, category: '物品', emojis: '🩹🤕', answer: 'OK繃' },

  // =================================================================
  // 8. 職業與角色 (Professions)
  // =================================================================
  { id: 291, category: '職業', emojis: '👨‍⚕️💉🏥', answer: '醫生' },
  { id: 292, category: '職業', emojis: '👨‍🍳🍳🔥', answer: '廚師' },
  { id: 293, category: '職業', emojis: '👮‍♂️🚔🚨', answer: '警察' },
  { id: 294, category: '職業', emojis: '🚀👨‍🚀🌙', answer: '太空人' },
  { id: 295, category: '職業', emojis: '🎤🎶✨', answer: '歌手' },
  { id: 296, category: '職業', emojis: '👨‍🏫🏫📚', answer: '老師' },
  { id: 297, category: '職業', emojis: '👨‍🚒🔥🚒', answer: '消防員' },
  { id: 298, category: '職業', emojis: '🕵️‍♂️🔍', answer: '偵探' },
  { id: 299, category: '職業', emojis: '🧙‍♂️🔮', answer: '魔術師' },
  { id: 300, category: '職業', emojis: '👨‍⚖️🔨', answer: '法官' },
  { id: 301, category: '職業', emojis: '✈️👨‍✈️', answer: '機師' },
  { id: 302, category: '職業', emojis: '✈️💁‍♀️', answer: '空服員' },
  { id: 303, category: '職業', emojis: '👨‍🎨🎨', answer: '畫家' },
  { id: 304, category: '職業', emojis: '👨‍💻💻', answer: '工程師' },
  { id: 305, category: '職業', emojis: '💇‍♂️✂️', answer: '理髮師' },
  { id: 306, category: '職業', emojis: '👨‍🌾🚜', answer: '農夫' },
  { id: 307, category: '職業', emojis: '🧗‍♂️⛰️', answer: '登山客' },
  { id: 308, category: '職業', emojis: '🏋️‍♂️💪', answer: '健身教練' },
  { id: 309, category: '職業', emojis: '🤡🎪', answer: '小丑' },
  { id: 310, category: '職業', emojis: '🧟‍♂️🧟‍♀️', answer: '殭屍' },
  { id: 311, category: '職業', emojis: '🧛‍♂️🧛‍♀️', answer: '吸血鬼' },
  { id: 312, category: '職業', emojis: '🧜‍♀️🌊', answer: '美人魚' },
  { id: 313, category: '職業', emojis: '👼🪽', answer: '天使' },
  { id: 314, category: '職業', emojis: '😈🔥', answer: '惡魔' },
  { id: 315, category: '職業', emojis: '👽🛸', answer: '外星人' },
  { id: 316, category: '職業', emojis: '🤖🦾', answer: '機器人' },
  { id: 317, category: '職業', emojis: '🥷⚔️', answer: '忍者' },
  { id: 318, category: '職業', emojis: '🤴👑', answer: '國王' },
  { id: 319, category: '職業', emojis: '🏴‍☠️🦜💰', answer: '海盜' },
  { id: 320, category: '職業', emojis: '🤠🐎🔫', answer: '牛仔' },
  { id: 321, category: '職業', emojis: '📸📰', answer: '記者' },
  { id: 322, category: '職業', emojis: '🦷👨‍⚕️', answer: '牙醫' },
  { id: 323, category: '職業', emojis: '💊👨‍🔬', answer: '藥劑師' },
  { id: 324, category: '職業', emojis: '🚕👨‍✈️', answer: '司機' },
  { id: 325, category: '職業', emojis: '💃🩰', answer: '舞者' },
  
  // =================================================================
  // 9. 地點與自然 (Locations & Nature)
  // =================================================================
  { id: 326, category: '地點', emojis: '🗽🇺🇸', answer: '自由女神' },
  { id: 327, category: '地點', emojis: '🗼🇫🇷💕', answer: '艾菲爾鐵塔' },
  { id: 328, category: '地點', emojis: '🏯🌸🇯🇵', answer: '日本' },
  { id: 329, category: '地點', emojis: '🏖️☀️🌴', answer: '夏威夷' },
  { id: 330, category: '地點', emojis: '🏜️🐪🐫', answer: '撒哈拉沙漠' },
  { id: 331, category: '地點', emojis: '🕋☪️', answer: '麥加' },
  { id: 332, category: '地點', emojis: '🏰🤴👸', answer: '迪士尼樂園' },
  { id: 333, category: '地點', emojis: '🏟️⚽🇧🇷', answer: '巴西' },
  { id: 334, category: '地點', emojis: '🦘🐨🇦🇺', answer: '澳洲' },
  { id: 335, category: '地點', emojis: '🐻‍❄️🧊❄️', answer: '北極' },
  { id: 336, category: '地點', emojis: '🐧🧊❄️', answer: '南極' },
  { id: 337, category: '地點', emojis: '🛸👽🏜️', answer: '51區' },
  { id: 338, category: '地點', emojis: '🌊🔺🚢❓', answer: '百慕達三角洲' },
  { id: 339, category: '地點', emojis: '🌋🦖', answer: '侏羅紀' },
  { id: 340, category: '地點', emojis: '🌚🌑🌒', answer: '月球' },
  { id: 341, category: '地點', emojis: '🪵🔥🏕️', answer: '露營地' },
  { id: 342, category: '地點', emojis: '📚🤫', answer: '圖書館' },
  { id: 343, category: '地點', emojis: '🏊‍♂️🏊‍♀️💧', answer: '游泳池' },
  { id: 344, category: '地點', emojis: '🦍🐘🦒', answer: '動物園' },
  { id: 345, category: '地點', emojis: '🖼️🎨🧐', answer: '美術館' },
  { id: 346, category: '地點', emojis: '🍿🎥💺', answer: '電影院' },
  { id: 347, category: '地點', emojis: '🛍️🏬', answer: '百貨公司' },
  { id: 348, category: '地點', emojis: '🏋️‍♂️🏃‍♀️', answer: '健身房' },
  { id: 349, category: '地點', emojis: '🎤🎵🍻', answer: 'KTV' },
  { id: 350, category: '地點', emojis: '🎰🎲💰', answer: '賭場' },

  // =================================================================
  // 10. 童話與神話 (Fairy Tales & Myths)
  // =================================================================
  { id: 351, category: '童話', emojis: '👧🐺👵', answer: '小紅帽' },
  { id: 352, category: '童話', emojis: '🐖🐖🐖🐺', answer: '三隻小豬' },
  { id: 353, category: '童話', emojis: '🤥🪵👃', answer: '皮諾丘' },
  { id: 354, category: '童話', emojis: '🧜‍♀️🤴💔', answer: '小美人魚' },
  { id: 355, category: '童話', emojis: '👠🕛🎃', answer: '仙履奇緣' },
  { id: 356, category: '童話', emojis: '👱‍♀️🐻🐻🐻', answer: '金髮姑娘' },
  { id: 357, category: '童話', emojis: '🧞‍♂️🏮', answer: '阿拉丁' },
  { id: 358, category: '童話', emojis: '🐢🐇🏁', answer: '龜兔賽跑' },
  { id: 359, category: '童話', emojis: '🤴🗡️🪨', answer: '石中劍' },
  { id: 360, category: '童話', emojis: '👹🍑👦', answer: '桃太郎' },
  { id: 361, category: '童話', emojis: '👸豌豆🛏️', answer: '豌豆公主' },
  { id: 362, category: '童話', emojis: '🎅🦌🎁', answer: '聖誕老人' },
  { id: 363, category: '童話', emojis: '🐇🕒🕳️', answer: '愛麗絲夢遊仙境' },
  { id: 364, category: '童話', emojis: '🦁🐭🤝', answer: '獅子與老鼠' },
  { id: 365, category: '童話', emojis: '🧙‍♀️🏠🍭', answer: '糖果屋' }
];

// 根據分類獲取題目
export const getQuestionsByCategory = (category) => {
  console.log(`[emojiData] 取得分類「${category}」的題目`);
  return EMOJI_QUESTIONS.filter(q => q.category === category);
};

// 取得所有分類
export const getAllCategories = () => {
  const categories = [...new Set(EMOJI_QUESTIONS.map(q => q.category))];
  console.log(`[emojiData] 所有分類:`, categories);
  return categories;
};

// 隨機洗牌題目
export const shuffleQuestions = (questions) => {
  console.log(`[emojiData] 洗牌 ${questions.length} 題`);
  const shuffled = [...questions].sort(() => Math.random() - 0.5);
  return shuffled;
};
